[package]
name = "query"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2021"
description = "IOx Query Interface and Executor"

# This crate is designed to be independent of the rest of the IOx
# server and specific storage systems such as Mutable Buffer and Read Buffer.
#
# The rationale for this is to:
#
# 1. Keep change/compile/link time down during development when working on just this crate
# 2. Allow for query logic testing without bringing in all the storage systems.

[dependencies] # In alphabetical order
arrow = { version = "6.0", features = ["prettyprint"] }
arrow_util = { path = "../arrow_util" }
async-trait = "0.1"
chrono = "0.4"
croaring = "0.5"
data_types = { path = "../data_types" }
datafusion = { path = "../datafusion" }
datafusion_util = { path = "../datafusion_util" }
dml = { path = "../dml" }
futures = "0.3"
hashbrown = "0.11"
observability_deps = { path = "../observability_deps" }
parking_lot = "0.11.2"
pin-project = "1.0"
regex = "1"
schema = { path = "../schema" }
snafu = "0.6.9"
tokio = { version = "1.13", features = ["macros"] }
tokio-stream = "0.1.8"
tokio-util = { version = "0.6.9" }
trace = { path = "../trace" }
predicate = { path = "../predicate" }


# use libc on unix like platforms to set worker priority in DedicatedExecutor
[target."cfg(unix)".dependencies.libc]
version = "0.2"

[dev-dependencies] # In alphabetical order
itertools = "0.10.1"
test_helpers = { path = "../test_helpers" }
